#!/bin/bash
PYTHON_EXECUTABLE=python3
FILES=${1:-day*.py}

for f in $FILES
do
    echo "------------------"
    echo "Running $f"
    filename="${f%.*}"
    export TIMEFORMAT="|$f|%Es|"
    time $PYTHON_EXECUTABLE $f < in/$filename.in
done