#!/bin/bash
PYTHON_EXECUTABLE=python3
#PYTHON_EXECUTABLE=/usr/bin/python3
FILES=${1:-day*.py}

for f in $FILES
do
    echo "------------------"
    echo "Running $f"
    filename="${f%.*}"
    lines=$(grep -c '^' $f)
    export TIMEFORMAT="|[$f](https://github.com/juanplopes/advent-of-code-2022/blob/main/$f)|$lines|%E|"
    time $PYTHON_EXECUTABLE $f < in/$filename.in
done